services:
    mobile:
        image: edgeslam-mobile
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./start_mobile_container.sh:/home/edgeslam/start_mobile_container.sh
            - ./mobile_input_distributed.txt:/home/edgeslam/mobile_input.txt
        command: ["bash", "start_mobile_container.sh"]
        network_mode: "host"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        privileged: true
        devices:
            - /dev/hidraw5:/dev/hidraw5
            - /dev/video0:/dev/video0
            - /dev/video1:/dev/video1
    edge:
        image: edgeslam-edge
        volumes:
            - ./start_edge_container.sh:/home/edgeslam/start_edge_container.sh
            - ./edge_input_distributed.txt:/home/edgeslam/edge_input.txt
        command: ["bash", "start_edge_container.sh"]
        network_mode: "host"