services:
  mobile:
    image: edgeslam
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./rgbd_dataset_freiburg2_desk.bag:/home/edgeslam/rgbd_dataset_freiburg2_desk.bag
      - ./TUM2.yaml:/home/edgeslam/Examples/RGB-D/TUM2.yaml
      - ./start_mobile_container.sh:/home/edgeslam/start_mobile_container.sh
      - ./mobile_input.txt:/home/edgeslam/mobile_input.txt
      - edgeslam_mobile:/home/edgeslam/Examples/ROS/Edge_SLAM
    command: ["bash", "start_mobile_container.sh"]
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      mynet:
        ipv4_address: 1.1.0.2
  edge:
    image: edgeslam
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./start_edge_container.sh:/home/edgeslam/start_edge_container.sh
      - ./edge_input.txt:/home/edgeslam/edge_input.txt
      - edgeslam_edge:/home/edgeslam/Examples/ROS/Edge_SLAM
    command: ["bash", "start_edge_container.sh"]
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      mynet:
        ipv4_address: 1.1.0.3
  
volumes:
  edgeslam_edge:
  edgeslam_mobile:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 1.1.0.0/16